#!/usr/bin/env bash
#####################################################
#   ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗   #
#   ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║   #
#   ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║   #
#   ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║   #
#   ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║   #
#   ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝   #                                    
#####################################################

## Environtment
export PATH="${PATH}:$HOME/.config/bspwm/bin"
export PATH="${PATH}:$HOME/.config/rofi/bin"
export EDITOR="nvim"
export BROWSER="firefox"
export PAGER="bat"

##########################################################################
#	autostart
##########################################################################

# xrandr setup
$HOME/.local/bin/./set-monitors.sh &

killall -9 sxhkd dunst picom xfce-polkit polkit-gnome-authentication-1 eww
if [[ ! `pidof xfce-polkit` ]]; then
	/usr/lib/xfce-polkit/xfce-polkit &
fi
sxhkd &
picom &
dunst &
set-monitors &
xsetroot -cursor_name left_ptr &
eww daemon &
$HOME/.fehbg &


##########################################################################
#	functions
##########################################################################
xrdb ~/.Xresources
getcolors() {
	FOREGROUND=$(xrdb -query | grep 'foreground:'| awk '{print $NF}')
	BACKGROUND=$(xrdb -query | grep 'background:'| awk '{print $NF}')
	BLACK=$(xrdb -query | grep 'color0:'| awk '{print $NF}')
	RED=$(xrdb -query | grep 'color1:'| awk '{print $NF}')
	GREEN=$(xrdb -query | grep 'color2:'| awk '{print $NF}')
	YELLOW=$(xrdb -query | grep 'color3:'| awk '{print $NF}')
	BLUE=$(xrdb -query | grep 'color4:'| awk '{print $NF}')
	MAGENTA=$(xrdb -query | grep 'color5:'| awk '{print $NF}')
	CYAN=$(xrdb -query | grep 'color6:'| awk '{print $NF}')
	WHITE=$(xrdb -query | grep 'color7:'| awk '{print $NF}')
}
getcolors

rule() { bspc rule -a "$@" & }
config() { bspc config "$@" & }

###########################################################################
#	config
###########################################################################
bspc monitor DisplayPort-0 -a 1 2 3 4
bspc monitor HDMI-A-0 -a 5 6 7 8
# or #
for monitor in $(xrandr -q | grep " connected" | cut -d ' ' -f1); do
    xrandr --output "$monitor" --set "Broadcast RGB" "Full"
    bspc monitor "$monitor" -d 1 2 3 4 5
    bspc config -m "$monitor" window_gap 25
done
###########################################################################
config border_width 2
config window_gap 12
config split_ratio 0.60

config focused_border_color "$GREEN" 
config normal_border_color "$FOREGROUND"
config active_border_color "$BLUE"
config presel_feedback_color "$BACKGROUND"

config borderless_monocle true
config gapless_monocle true
config paddingless_monocle true
config single_monocle false
config focus_follows_pointer true
config pointer_follows_focus true
config remove_disabled_monitors true
config remove_unplugged_monitors true
config honor_size_hints true

config pointer_modifier Mod4
###########################################################################
#	rules
###########################################################################

rule -r *:*
rule firefox follow=on focus=on
rule chromium follow=on focus=on
rule code follow=on focus=on
rule Discord state=fullscreen
rule vlc follow=on focus=on state=fullscreen

# floats
declare -a floats=( Lxappearance nm-connection-editor \
		   Arandr Pavucontrol 'Firefox:Places')
for i in ${floats[@]}; do
   rule $i state=floating center=true focus=on rectangle 450x550+50+50; done

declare -a float_term=( scratchpad kitty )
for i in ${float_term[@]}; do
   rule $i state=floating center=true focus=on rectangle 300x550+50+50; done

