#!/usr/bin/env bash
#####################################################
#   ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗   #
#   ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║   #
#   ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║   #
#   ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║   #
#   ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║   #
#   ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝   #                                    
#####################################################

## Environtment
export PATH="${PATH}:$HOME/.config/bspwm/bin"
##########################################################################
#	autostart
##########################################################################

# xrandr setup
$HOME/.local/bin/./set-monitors.sh &

killall -9 sxhkd dunst picom xfce-polkit eww
if [[ ! `pidof xfce-polkit` ]]; then
	/usr/lib/xfce-polkit/xfce-polkit &
fi
sxhkd &
picom &
dunst &
xsetroot -cursor_name left_ptr
eww daemon


##########################################################################
#	functions
##########################################################################
xrdb ~/.Xresources
getcolors() {
	FOREGROUND=$(xrdb -query | grep 'foreground:'| awk '{print $NF}')
	BACKGROUND=$(xrdb -query | grep 'background:'| awk '{print $NF}')
	BLACK=$(xrdb -query | grep 'color0:'| awk '{print $NF}')
	RED=$(xrdb -query | grep 'color1:'| awk '{print $NF}')
	GREEN=$(xrdb -query | grep 'color2:'| awk '{print $NF}')
	YELLOW=$(xrdb -query | grep 'color3:'| awk '{print $NF}')
	BLUE=$(xrdb -query | grep 'color4:'| awk '{print $NF}')
	MAGENTA=$(xrdb -query | grep 'color5:'| awk '{print $NF}')
	CYAN=$(xrdb -query | grep 'color6:'| awk '{print $NF}')
	WHITE=$(xrdb -query | grep 'color7:'| awk '{print $NF}')
}
getcolors

rule() { bspc rule -a "$@" & }
config() { bspc config "$@" & }

###########################################################################
#	config
###########################################################################
bspc monitor DisplayPort-0 -d '' '' '' '' '' '' '' ''
bspc monitor HDMI-A-0 -d '' '' '' '' '' '' '' ''

bspc config border_width 1
bspc config window_gap 12
bspc config split_ratio 0.50

bspc config focused_border_color "$GREEN" 
bspc config normal_border_color "$FOREGROUND"
bspc config active_border_color "$BLUE"
bspc config presel_feedback_color "$BACKGROUND"

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true

###########################################################################
#	rules
###########################################################################

bspc rule -r *:*
rule firefox follow=on focus=on
rule chromium follow=on focus=on
rule code follow=on focus=on
rule vlc follow=on focus=on state=fullscreen

# floats
declare -a floats=(kitty Lxrandr Lxappearance feh nm-connection-editor \
		   Arandr Pavucontrol alacritty-float 'Firefox:Places')
for i in ${floats[@]}; do
   rule $i state=floating focus=on; done
